apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-8egl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-magh-tenant/rhtap-demo-app/hacbs-test-project-8egl@sha256:07ff75f40dac3d23c41b47faeb25385c61ae7c97fcb9a2b572d47ba08424e9cf
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
