apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8egl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8egl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8egl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8egl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8egl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-magh-tenant/rhtap-demo-app/hacbs-test-project-8egl@sha256:0d8b61ee9e0b5ed3e82d5d1df0a0790961a1353aa5bc29ffeef447b07fe9e63c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
